version: "3.2"
services:
    web:
        container_name: web-vendingmachine
        image: nginx:1.10.3
        ports:
        - "${WEB_PORT}:80"
        - "${WEB_SSL_PORT}:443"
        volumes:
        - .:/var/www/html
        - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/config/nginx/vhost7.conf:/etc/nginx/conf.d/default.conf
        - ./docker/log/nginx/:/var/log/nginx/
        links:
        - php
    php:
        container_name: php-vendingmachine
        build: ./docker/docker-images/php7/
        ports:
        - "${PHP_PORT}:4730"
        volumes:
        - .:/var/www/html
        - ./docker/config/php/php7.ini:/usr/local/etc/php/php.ini:ro
        - ./docker/config/php/custom-config:/usr/local/etc/php/custom-config.d:ro
        environment:
        - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/usr/local/etc/php/custom-config.d
        working_dir: /var/www/html